services:
  sa-db:
    image: mongo:8.2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - sa-db-data:/data/db
    networks:
      - sa-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username $${MONGO_INITDB_ROOT_USERNAME} --password $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand({ ping: 1 }).ok\" mongodb://localhost:27017/admin | grep 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  sa-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
    depends_on:
      sa-db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    networks:
      - sa-network

networks:
  sa-network:
    name: sa-network

volumes:
  sa-db-data:
