import { IDesignSystemContext } from '../types';

export const DEFAULT_DESIGN_SYSTEM_CONTEXT: IDesignSystemContext = {
  knownTokens: [
    '--color-text-primary',
    '--color-text-secondary',
    '--color-surface-default',
    '--color-surface-muted',
    '--color-border-subtle',
    '--color-border-danger',
    '--color-status-success',
    '--color-status-warning',
    '--color-status-danger',
    '--spacing-4',
    '--spacing-8',
    '--spacing-12',
    '--spacing-16',
    '--spacing-24',
    '--radius-8',
    '--radius-12',
    '--shadow-sm',
    '--font-size-body',
    '--font-size-label',
    '--font-weight-medium',
    'color.text.primary',
    'color.text.secondary',
    'color.surface.default',
    'color.surface.muted',
    'color.border.subtle',
    'color.border.danger',
    'color.status.success',
    'color.status.warning',
    'color.status.danger',
    'spacing.4',
    'spacing.8',
    'spacing.12',
    'spacing.16',
    'spacing.24',
    'radius.8',
    'radius.12',
    'shadow.sm',
    'typography.body',
    'typography.label',
    'font.weight.medium',
  ],
  tokenValues: {
    '--color-border-danger': '#dc2626',
    '--color-border-subtle': '#d1d5db',
    '--color-status-danger': '#dc2626',
    '--color-status-success': '#16a34a',
    '--color-status-warning': '#d97706',
    '--color-surface-default': '#ffffff',
    '--color-surface-muted': '#f3f4f6',
    '--color-text-primary': '#111827',
    '--color-text-secondary': '#6b7280',
    '--font-size-body': '14px',
    '--font-size-label': '12px',
    '--font-weight-medium': '500',
    '--radius-12': '12px',
    '--radius-8': '8px',
    '--shadow-sm': '0 1px 2px rgba(17, 24, 39, 0.08)',
    '--spacing-12': '12px',
    '--spacing-16': '16px',
    '--spacing-24': '24px',
    '--spacing-4': '4px',
    '--spacing-8': '8px',
    'color.border.danger': '#dc2626',
    'color.border.subtle': '#d1d5db',
    'color.status.danger': '#dc2626',
    'color.status.success': '#16a34a',
    'color.status.warning': '#d97706',
    'color.surface.default': '#ffffff',
    'color.surface.muted': '#f3f4f6',
    'color.text.primary': '#111827',
    'color.text.secondary': '#6b7280',
    'font.weight.medium': '500',
    'radius.12': '12px',
    'radius.8': '8px',
    'shadow.sm': '0 1px 2px rgba(17, 24, 39, 0.08)',
    'spacing.12': '12px',
    'spacing.16': '16px',
    'spacing.24': '24px',
    'spacing.4': '4px',
    'spacing.8': '8px',
    'typography.body': '14px',
    'typography.label': '12px',
  },
};
